let DATA=null,state=JSON.parse(localStorage.getItem('sea2027-pwa-v2')||'{"here":"Pre-departure · Melbourne","done":{},"content":{}}'),history=[];
const app=document.querySelector('#app'),nav=document.querySelector('#nav');
const save=()=>localStorage.setItem('sea2027-pwa-v2',JSON.stringify(state));
async function boot(){
  try{
    const r=await fetch('./data/itinerary.json',{cache:'no-store'});
    if(!r.ok) throw new Error('itinerary.json returned '+r.status);
    DATA=await r.json();
    cover();
  }catch(err){
    console.error(err);
    app.innerHTML='<div style="padding:24px;font-family:system-ui"><h1>App could not load</h1><p>'+String(err.message||err)+'</p><p>Refresh once. If this remains, check that <b>data/itinerary.json</b> exists in the GitHub repository.</p></div>';
  }
}
function cover(){
  nav.hidden=true;
  app.innerHTML=`<section class="cover"><div><div class="kicker">Live trip companion · 2027</div><h1>Southeast<br>Asia 2027</h1><p>Know what to do here, where to go next, and what not to miss.</p></div><button class="enter" id="enter">ENTER JOURNEY →</button></section>`;
  const enterButton=document.getElementById('enter');
  enterButton.addEventListener('click',()=>{nav.hidden=false;history=[];now(false)});
}
function shell(title,body,showBack=true){
  app.innerHTML=`<header class="top">${showBack?'<button class="back" id="backButton">← Back</button>':''}<b>${title}</b></header>${body}`;
  if(showBack){
    const backButton=document.getElementById('backButton');
    if(backButton) backButton.addEventListener('click',goBack);
  }
  window.scrollTo(0,0);
}
function push(fn,args=[]){history.push({fn,args})}function goBack(){let h=history.pop();h?h.fn(...h.args):now(false)}
function countryByName(n){return DATA.countries.find(c=>c.name===n)}
function parseHere(){let p=state.here.split(' · ');if(p.length<2)return null;let c=countryByName(p[0]);if(!c)return null;let i=DATA.stops[c.id].findIndex(s=>s[0]===p.slice(1).join(' · '));return i<0?null:{c,i,s:DATA.stops[c.id][i]}}
function eid(c,i){return `${c.id}-${i}`} function isDone(c,i){return !!state.done[eid(c,i)]}
function allRows(){return DATA.countries.flatMap(c=>DATA.stops[c.id].map((s,i)=>({c,s,i,id:eid(c,i)})))}
function nextUndone(){let here=parseHere(),rows=allRows();if(!here)return rows[0];let pos=rows.findIndex(r=>r.c.id===here.c.id&&r.i===here.i);return rows.slice(pos+1).find(r=>!state.done[r.id])||rows.find(r=>!state.done[r.id])}
function daysTo(date){return Math.ceil((new Date(date+'T00:00:00')-new Date())/86400000)}
function top(){let rows=allRows(),done=rows.filter(r=>state.done[r.id]).length;return {rows,done,pct:Math.round(done/rows.length*100)}}
function now(record=true){if(record)push(now,[false]);let h=parseHere(),t=top(),next=nextUndone();let context=h?`${h.c.flag} ${h.c.name} · ${h.s[0]}`:'Melbourne · pre-departure';shell('YOU ARE HERE',`<div class="hero fallback dashboardHero"><div class="heroText"><div class="kicker">Current position</div><h2>${context}</h2><p>${h?'What matters here, then the smartest next move.':'Departure 28 January 2027. Your master itinerary is loaded and ready.'}</p></div></div><div class="actionGrid"><button class="action" onclick="doHere()"><span class="icon">✓</span><strong>DO HERE</strong><small>${h?h.s[1]:'See your first experiences'}</small></button><button class="action" onclick="goNext()"><span class="icon">→</span><strong>GO NEXT</strong><small>${next?next.s[0]:'Route complete'}</small></button><button class="action" onclick="dontMiss()"><span class="icon">!</span><strong>DON'T MISS</strong><small>High-priority + fixed-date items</small></button><button class="action" onclick="journey()"><span class="icon">⌁</span><strong>MY JOURNEY</strong><small>${t.done}/${t.rows.length} experiences complete</small></button></div><h3>Journey progress</h3><div class="card"><div class="countryProgress"><b>${t.pct}% complete</b><span class="meta">${t.done} of ${t.rows.length}</span></div><div class="progress" style="margin-top:10px"><i style="width:${t.pct}%"></i></div></div><button class="btn" style="width:100%" onclick="setLocation()">Change “You are here”</button>`,false)}
function doHere(){push(now,[false]);let h=parseHere();if(!h){let r=allRows()[0];return experience(r.c,r.i,'DO HERE')}experience(h.c,h.i,'DO HERE')}
function experience(c,i,title='EXPERIENCE'){let s=DATA.stops[c.id][i],done=isDone(c,i),content=!!state.content[eid(c,i)];shell(title,`<div class="hero fallback"><div class="heroText"><div class="kicker">${c.flag} ${c.name} · ${s[3]} priority</div><h2>${s[0]}</h2><p>${s[1]} nights/days</p></div></div><div class="card"><span class="badge ${s[3]==='S+'?'splus':''}">${s[3]}</span><h3 style="margin-top:10px">${s[1]}</h3><p>${s[2]}</p><div class="social"><b>Content mode</b><br>Capture: establishing wide → local/human detail → movement/reveal → one spoken observation. Aim for the experience, not a generic montage.</div></div><button class="btn primary completeBtn" onclick="toggleDone('${eid(c,i)}',${!done},'${c.id}',${i})">${done?'✓ COMPLETED':'MARK EXPERIENCE COMPLETE'}</button><button class="btn completeBtn" onclick="toggleContent('${eid(c,i)}',${!content},'${c.id}',${i})">${content?'✓ FOOTAGE CAPTURED':'MARK FOOTAGE CAPTURED'}</button>`)}
function toggleDone(id,v,cid,i){state.done[id]=v;save();experience(DATA.countries.find(c=>c.id===cid),i,'DO HERE')}function toggleContent(id,v,cid,i){state.content[id]=v;save();experience(DATA.countries.find(c=>c.id===cid),i,'DO HERE')}
function goNext(){push(now,[false]);let r=nextUndone();if(!r)return shell('GO NEXT','<div class="notice">Everything in the current master list is complete.</div>');let unique=/S\+|S/.test(r.s[3]);shell('GO NEXT',`<div class="card decision"><div class="sectionLabel">Recommended next</div><h2>${r.c.flag} ${r.s[0]}</h2><p><b>${r.s[1]}</b></p><p>${r.s[2]}</p><div class="why"><div><b>Priority</b><br>${r.s[3]}</div><div><b>Unique value</b><br>${unique?'High':'Useful / optional'}</div><div><b>Sequence</b><br>Next unfinished stop</div><div><b>Trip style</b><br>Slow-travel compatible</div></div></div><button class="btn primary" style="width:100%" onclick="state.here='${r.c.name} · ${r.s[0].replaceAll("'","\\'")}';save();now(false)">I'M HERE NOW →</button><button class="btn" style="width:100%;margin-top:8px" onclick="alternatives('${r.c.id}',${r.i})">SHOW ALTERNATIVES</button>`)}
function alternatives(cid,i){let c=DATA.countries.find(x=>x.id===cid),arr=DATA.stops[cid].slice(i+1,i+4);shell('ALTERNATIVES',`<p class="meta">Later stops in the same chapter. This does not rewrite your master route.</p>${arr.map((s,k)=>`<div class="card"><span class="badge ${s[3]==='S+'?'splus':''}">${s[3]}</span><h3 style="margin:8px 0">${s[0]}</h3><p>${s[2]}</p></div>`).join('')}`)}
function dontMiss(){push(now,[false]);let priority=allRows().filter(r=>!state.done[r.id]&&(r.s[3]==='S+'||r.s[3]==='S'));shell("DON'T MISS",`<div class="hero fallback"><div class="heroText"><div class="kicker">FOMO CONTROL</div><h2>${priority.length} major experiences remain</h2><p>Only S+ and S experiences are surfaced here, plus your fixed commitments.</p></div></div><h3>Fixed commitments</h3>${DATA.constraints.map(x=>`<div class="card locked"><b>${x.label}</b><div class="meta">${x.date||x.start+' → '+x.end}</div></div>`).join('')}<h3>High-priority experiences</h3>${priority.map(r=>`<div class="card ${r.s[3]==='S+'?'urgent':''}"><span class="badge ${r.s[3]==='S+'?'splus':''}">${r.s[3]}</span><b style="display:block;margin-top:7px">${r.s[0]}</b><div class="meta">${r.c.flag} ${r.c.name}</div><p>${r.s[1]} — ${r.s[2]}</p><button class="btn" onclick="experience(DATA.countries.find(c=>c.id==='${r.c.id}'),${r.i},'DON’T MISS')">Open →</button></div>`).join('')}`)}
function journey(){push(now,[false]);shell('MY JOURNEY',`<div class="hero fallback"><div class="heroText"><div class="kicker">Experience passport</div><h2>Your journey</h2><p>Countries, progress and every experience remain accessible here.</p></div></div>${DATA.countries.map(c=>{let a=DATA.stops[c.id],d=a.filter((s,i)=>isDone(c,i)).length,p=Math.round(d/a.length*100);return `<div class="card"><div class="countryProgress"><div><b>${c.flag} ${c.name}</b><div class="meta">${d}/${a.length} completed</div></div><b>${p}%</b></div><div class="progress" style="margin:10px 0"><i style="width:${p}%"></i></div><button class="btn" onclick="country('${c.id}')">Open country →</button></div>`}).join('')}`)}
function country(id){let c=DATA.countries.find(x=>x.id===id);push(journey);shell(`${c.flag} ${c.name}`,`<div class="hero fallback"><div class="heroText"><div class="kicker">Country chapter</div><h2>${c.flag} ${c.name}</h2><p>${c.subtitle}</p></div></div><div class="chips">${c.key.map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="timeline"><h3>Travel sequence</h3>${DATA.stops[id].map((s,i)=>`<div class="card ${isDone(c,i)?'done':''}"><span class="badge ${s[3]==='S+'?'splus':''}">${s[3]}</span><b style="display:block;margin-top:6px">${i+1}. ${s[0]}</b><div class="meta">${s[1]} nights/days</div><p>${s[2]}</p><button class="btn" onclick="experience(DATA.countries.find(c=>c.id==='${id}'),${i},'${c.name.toUpperCase()}')">Open →</button></div>`).join('')}</div>`)}
function setLocation(){push(now,[false]);let opts=['Pre-departure · Melbourne',...DATA.countries.flatMap(c=>DATA.stops[c.id].map(s=>`${c.name} · ${s[0]}`))];shell('SET LOCATION',`<div class="card"><label class="sectionLabel">You are here</label><select id="loc" style="margin-top:8px">${opts.map(x=>`<option ${x===state.here?'selected':''}>${x}</option>`).join('')}</select><button class="btn primary" id="set" style="width:100%;margin-top:10px">UPDATE LOCATION</button></div>`);document.getElementById('set').onclick=()=>{state.here=document.getElementById('loc').value;save();history=[];now(false)}}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>({now:()=>now(false),do:doHere,next:goNext,miss:dontMiss,journey}[b.dataset.nav])());
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});boot();