from pathlib import Path
import re
p=Path('data/travel-companion-v1-shell.js'); s=p.read_text()

s=s.replace("const V={country:null,dest:null,countryTab:'overview',destTab:'overview',filter:'All',passType:'food',last:'main'};","const V={country:null,dest:null,countryTab:'overview',destTab:'overview',filter:'All',passType:'food',planMode:'2',last:'main'};",1)

s=s.replace('<button class="tc1DrawerBtn" data-global="book"><small>Lead-time items</small><b>Book Ahead</b></button><button class="tc1DrawerBtn" data-global="main">','<button class="tc1DrawerBtn" data-global="book"><small>Lead-time items</small><b>Book Ahead</b></button><button class="tc1DrawerBtn" data-global="miss"><small>Highest-priority unfinished</small><b>Don\'t Miss</b></button><button class="tc1DrawerBtn" data-global="main">',1)
s=s.replace("else if(x==='book')renderBookAhead()","else if(x==='book')renderBookAhead();else if(x==='miss')renderDontMiss()",1)

old="function progress(id,i){const its=getItems(id,i),done=its.filter((it,j)=>hasState('done',id,i,it,j)).length;return {done,total:its.length,pct:its.length?Math.round(done/its.length*100):0}}\nfunction destinationTabs(id,i){return [['overview','OVERVIEW'],['experiences','EXPERIENCES'],['food','FOOD & DRINK'],['map','MAP']]}"
new=r'''function progress(id,i){const its=getItems(id,i),done=its.filter((it,j)=>hasState('done',id,i,it,j)).length;return {done,total:its.length,pct:its.length?Math.round(done/its.length*100):0}}
function destinationFinished(id,i){const its=getItems(id,i);return !!its.length&&its.every((it,j)=>hasState('done',id,i,it,it.index??j)||hasState('skip',id,i,it,it.index??j))}
function nextJourneyDestination(id,i){const ci=JOURNEY_ORDER.indexOf(id);for(let cix=Math.max(0,ci);cix<JOURNEY_ORDER.length;cix++){const cid=JOURNEY_ORDER[cix],start=cid===id?i+1:0;for(let n=start;n<destinations(cid).length;n++)if(!destinationFinished(cid,n))return {id:cid,i:n,c:country(cid),d:destinations(cid)[n]}}return null}
function planScore(id,i,it){const r=personalRating(id,i,it,it.index);return ratingScore(r)*10+((it.tags||[]).includes('Must Do')||it.tier==='S+'?4:it.tier==='S'?3:it.tier==='A'?2:1)}
function planStateKey(id,i,it){return stableExperienceKey(id,i,it)}
function planState(id,i,it){return state.schedule?.[planStateKey(id,i,it)]||{status:'auto',day:null}}
function setPlanState(id,i,it,val){state.schedule=state.schedule||{};state.schedule[planStateKey(id,i,it)]={...(state.schedule[planStateKey(id,i,it)]||{}),...val};save()}
function planItems(id,i){return getItems(id,i).filter((it,j)=>personalRating(id,i,it,it.index??j)!=='pass'&&!hasState('done',id,i,it,it.index??j)&&!hasState('skip',id,i,it,it.index??j)).sort((a,b)=>planScore(id,i,b)-planScore(id,i,a))}
function scheduleModel(id,i,mode){const all=planItems(id,i),days=mode==='custom'?Math.max(1,Math.ceil(all.length/3)):Number(mode)||2,capacity=mode==='custom'?all.length:days*3,active=all.filter(it=>!['remove','swap'].includes(planState(id,i,it).status)),selected=active.slice(0,capacity),reserve=active.slice(capacity);return {all,days,selected,reserve}}
function scheduleCommand(id,i,j,cmd,mode){const it=getItems(id,i).find(x=>x.index===j);if(!it)return;const model=scheduleModel(id,i,mode),current=model.selected.findIndex(x=>x.index===j),assigned=planState(id,i,it).day||Math.floor(Math.max(0,current)/3)+1;if(cmd==='keep')setPlanState(id,i,it,{status:'keep'});else if(cmd==='remove')setPlanState(id,i,it,{status:'remove',day:null});else if(cmd==='move')setPlanState(id,i,it,{status:'keep',day:assigned%model.days+1});else if(cmd==='swap'){const replacement=model.reserve[0];setPlanState(id,i,it,{status:'swap',day:null});if(replacement)setPlanState(id,i,replacement,{status:'keep',day:assigned})}}
function scheduleView(id,i,mode='2'){const d=destinations(id)[i],m=scheduleModel(id,i,mode),tabs=[['1','1 DAY'],['2','2 DAYS'],['3','3 DAYS'],['custom','BUILD MY OWN']],byDay=Array.from({length:m.days},()=>[]);m.selected.forEach((it,n)=>{const st=planState(id,i,it),day=Math.max(1,Math.min(m.days,st.day||Math.floor(n/3)+1));byDay[day-1].push(it)});return `<div class="tc1Plan"><div class="tc1PassHead"><h2>Proposed schedule</h2><p>Built from your ratings first, then the locked priority. Adjust it without changing Saved, Done or your ratings.</p></div><div class="tc1PlanModes">${tabs.map(([k,l])=>`<button class="${mode===k?'on':''}" data-plan-mode="${k}">${l}</button>`).join('')}</div>${byDay.map((items,di)=>`<section class="tc1PlanDay"><div class="tc1Scope">DAY ${di+1}</div>${items.length?items.map(it=>{const st=planState(id,i,it);return `<article class="tc1PlanItem"><div><small>${esc((it.tags||[]).slice(0,2).join(' · ')||it.tier||'Experience')}</small><h3>${esc(it.title)}</h3><p>${esc(it.summary)}</p></div><div class="tc1PlanActions"><button class="${st.status==='keep'?'on':''}" data-plan-action="keep" data-plan-exp="${it.index}">KEEP</button><button data-plan-action="swap" data-plan-exp="${it.index}">SWAP</button><button data-plan-action="move" data-plan-exp="${it.index}">MOVE</button><button data-plan-action="remove" data-plan-exp="${it.index}">REMOVE</button></div></article>`}).join(''):'<div class="tc1Empty" style="margin:8px 0">Leave this day open.</div>'}</section>`).join('')}${m.reserve.length?`<div class="tc1PlanReserve"><div class="tc1Scope">RESERVE / SWAP IN</div>${m.reserve.slice(0,6).map(it=>`<div>${esc(it.title)}</div>`).join('')}</div>`:''}</div>`}
function destinationTabs(id,i){return [['overview','OVERVIEW'],['experiences','EXPERIENCES'],['food','FOOD & DRINK'],['plan','PLAN'],['map','MAP']]}
'''
assert old in s,'progress tabs marker missing';s=s.replace(old,new,1)

s=s.replace("miss=(must.length?must:its).filter((it,j)=>!hasState('done',id,i,it,it.index??j)&&!hasState('skip',id,i,it,it.index??j)).slice(0,3),next=destinations(id)[i+1];","miss=(must.length?must:its).filter((it,j)=>!hasState('done',id,i,it,it.index??j)&&!hasState('skip',id,i,it,it.index??j)).slice(0,3),next=nextJourneyDestination(id,i);",1)
s=s.replace("else if(tab==='food')body=passportView(id,i,passType);\n else body=mapView(id,i);","else if(tab==='food')body=passportView(id,i,passType);\n else if(tab==='plan')body=scheduleView(id,i,V.planMode);\n else body=mapView(id,i);",1)
s=s.replace("${next?`<button class=\"tc1Next\" data-next-dest><span><small>Next destination</small><b>${esc(next.name)}</b></span><span style=\"font-size:26px\">→</span></button>`:''}","${next?`<button class=\"tc1Next\" data-next-dest><span><small>Next unfinished · ${esc(next.c.name)}</small><b>${esc(next.d.name)}</b></span><span style=\"font-size:26px\">→</span></button>`:''}",1)
s=s.replace("const nx=document.querySelector('[data-next-dest]');if(nx)nx.onclick=()=>renderDestination(id,i+1,'overview');","document.querySelectorAll('[data-plan-mode]').forEach(b=>b.onclick=()=>{V.planMode=b.dataset.planMode;renderDestination(id,i,'plan',filter,passType)});\n document.querySelectorAll('[data-plan-action]').forEach(b=>b.onclick=()=>{scheduleCommand(id,i,Number(b.dataset.planExp),b.dataset.planAction,V.planMode);renderDestination(id,i,'plan',filter,passType)});\n const nx=document.querySelector('[data-next-dest]');if(nx&&next)nx.onclick=()=>renderDestination(next.id,next.i,'overview');",1)

# Global Don't Miss with fixed commitments + unfinished top-tier experiences.
marker="async function renderJourney(){"
insert=r'''async function renderDontMiss(){await readyCountry('vietnam');const a=allEntries().filter(x=>!x.done&&!x.skip&&(x.it.tier==='S+'||x.it.tier==='S')&&personalRating(x.country,x.i,x.it,x.j)!=='pass').sort((a,b)=>planScore(b.country,b.i,b.it)-planScore(a.country,a.i,a.it));setApp(`<section class="tc1Screen"><div class="tc1GlobalHead"><button class="tc1Round" data-global-back>←</button><div class="tc1Scope" style="color:#fff;margin-top:18px">FOMO CONTROL</div><h1>Don't Miss</h1><p>${a.length} high-priority unfinished experiences remain. Passed, Done and Skipped items stay out of this list.</p></div><div class="tc1GlobalList">${DATA.constraints.map(x=>`<article class="tc1GlobalCard tc1Constraint"><small>FIXED COMMITMENT · ${esc(x.date)}</small><h3>${esc(x.label)}</h3></article>`).join('')}${a.slice(0,80).map(globalCard).join('')}</div>${drawer()}</section>`);document.querySelector('[data-global-back]').onclick=restoreContext;}
'''
assert marker in s;s=s.replace(marker,insert+marker,1)

# Compatibility Go Next and Don't Miss use rebuilt semantics.
s=s.replace("window.goNext=function(){const x=current();if(!x)return renderMain();const n=destinations(x.id)[x.i+1];return n?renderDestination(x.id,x.i+1,'overview'):renderCountry(x.id,'route')};\nwindow.dontMiss=function(){const x=current();return x?renderDestination(x.id,x.i,'experiences','Must Do'):renderBookAhead()};","window.goNext=function(){const x=current();if(!x)return renderMain();const n=nextJourneyDestination(x.id,x.i);return n?renderDestination(n.id,n.i,'overview'):renderJourney()};\nwindow.dontMiss=renderDontMiss;",1)
p.write_text(s)

cssp=Path('data/travel-companion-v1-shell.css');css=cssp.read_text()
if '/* Destination schedule */' not in css:css+='''\n\n/* Destination schedule */\n.tc1Plan{padding-bottom:28px}.tc1PlanModes{display:flex;gap:7px;overflow:auto;padding:10px 18px 14px}.tc1PlanModes button{white-space:nowrap;border:1px solid var(--tc-line);background:var(--tc-paper2);color:var(--tc-ink);border-radius:999px;padding:9px 11px;font-size:8px;font-weight:900}.tc1PlanModes button.on{background:var(--tc-orange);border-color:var(--tc-orange);color:#fff}.tc1PlanDay{padding:8px 18px 10px}.tc1PlanItem{border:1px solid var(--tc-line);background:var(--tc-paper2);border-radius:16px;padding:14px;margin:9px 0}.tc1PlanItem small{font-size:8px;color:var(--tc-muted);text-transform:uppercase;letter-spacing:.08em}.tc1PlanItem h3{font:700 20px/1.05 Georgia,serif;margin:5px 0}.tc1PlanItem p{font-size:10px;line-height:1.42;color:var(--tc-muted);margin:5px 0 10px}.tc1PlanActions{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.tc1PlanActions button{border:1px solid var(--tc-line);background:#171719;color:var(--tc-ink);border-radius:9px;padding:8px 3px;font-size:7px;font-weight:900}.tc1PlanActions button.on{background:var(--tc-orange);border-color:var(--tc-orange)}.tc1PlanReserve{margin:12px 18px 0;border:1px dashed #3b3b40;border-radius:15px;padding:13px;color:var(--tc-muted);font-size:10px}.tc1PlanReserve>div:not(.tc1Scope){padding:6px 0;border-bottom:1px solid #26262a}.tc1PlanReserve>div:last-child{border:0}\n'''
cssp.write_text(css)
Path('docs/DESTINATION_PLAN_AUDIT.md').write_text('''# Destination planning audit\n\n- Destination tabs include a Proposed Schedule.\n- Modes: 1 DAY, 2 DAYS, 3 DAYS and BUILD MY OWN.\n- Suggestions use personal ratings first, then canonical priority.\n- Keep, Swap, Move and Remove actions persist independently from Saved/Done/rating state.\n- Go Next now resolves the next unfinished destination across chronological journey order.\n- Don't Miss is a global utility containing fixed commitments plus unfinished S+/S experiences, excluding Done, Skipped and personal Pass ratings.\n''')
