from pathlib import Path

p=Path('data/travel-companion-v1-shell.js')
s=p.read_text()

missing='''function experienceList(id,i,filter){let its=getItems(id,i);const filters=['All','Must Do','Food','Drink','History','Culture','Local Life','Book Ahead','Saved','Done','Skipped'];if(filter==='Saved')its=its.filter((it,j)=>hasState('saved',id,i,it,it.index??j));else if(filter==='Done')its=its.filter((it,j)=>hasState('done',id,i,it,it.index??j));else if(filter==='Skipped')its=its.filter((it,j)=>hasState('skip',id,i,it,it.index??j));else if(filter==='Book Ahead')its=its.filter(it=>isBookAhead(it));else if(filter!=='All')its=its.filter(it=>(it.tags||[]).some(t=>String(t).toLowerCase()===filter.toLowerCase())||(filter==='Must Do'&&(it.tier==='S+'||it.tier==='S'))||(filter==='Drink'&&(it.tags||[]).some(t=>/drink|coffee/i.test(t))));return `<button class="tc1RateAll tc1RateListLaunch" data-rate-deck><span><b>Rate ${getItems(id,i).length} experiences</b><small>One card at a time · ratings drive your destination priorities</small></span><span>→</span></button><div class="tc1Filters">${filters.map(f=>`<button class="tc1Filter ${f===filter?'on':''}" data-filter="${esc(f)}">${esc(f).toUpperCase()}</button>`).join('')}</div><div class="tc1ExpList">${its.length?its.map(it=>{const j=it.index;return `<article class="tc1Exp">${photoDiv(id,it.title,'tc1ExpPhoto')}<div class="tc1ExpCopy"><div class="tc1Tags">${(it.tags||[]).map(t=>`<i>${esc(t)}</i>`).join('')}</div><h3>${esc(it.title)}</h3>${ratingBadge(id,i,it,j)}<p>${esc(it.summary||'Open for the saved context and practical details.')}</p>${ratingFacts(it)}${it.flags?.length?`<div class="tc1Flags">${it.flags.map(f=>`<span>${esc(f)}</span>`).join('')}</div>`:''}<div class="tc1Actions"><button class="${hasState('saved',id,i,it,j)?'on':''}" data-save-exp="${j}">${hasState('saved',id,i,it,j)?'♥ SAVED':'♡ SAVE'}</button><button class="${hasState('done',id,i,it,j)?'on':''}" data-done-exp="${j}">${hasState('done',id,i,it,j)?'✓ DONE':'DONE'}</button><button class="${hasState('skip',id,i,it,j)?'on':''}" data-skip-exp="${j}">${hasState('skip',id,i,it,j)?'SKIPPED':'SKIP'}</button><button class="detail" data-open-exp="${j}">DETAILS →</button></div></div></article>`}).join(''):`<div class="tc1Empty">No matching experiences in this destination.</div>`}</div>`}
function wireExperienceActions(id,i,tab,filter,passType){
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>renderDestination(id,i,'experiences',b.dataset.filter,passType));
 document.querySelectorAll('[data-save-exp]').forEach(b=>b.onclick=()=>{const j=Number(b.dataset.saveExp),it=getItems(id,i).find(x=>x.index===j);if(it){toggleSaved(id,i,it,j);renderDestination(id,i,tab,filter,passType)}});
 document.querySelectorAll('[data-done-exp]').forEach(b=>b.onclick=()=>{const j=Number(b.dataset.doneExp),it=getItems(id,i).find(x=>x.index===j);if(it){toggleDone(id,i,it,j);renderDestination(id,i,tab,filter,passType)}});
 document.querySelectorAll('[data-skip-exp]').forEach(b=>b.onclick=()=>{const j=Number(b.dataset.skipExp),it=getItems(id,i).find(x=>x.index===j);if(it){toggleSkip(id,i,it,j);renderDestination(id,i,tab,filter,passType)}});
}
function passportView(id,i,type){
 if(id==='vietnam'&&i===0&&typeof SAIGON_FOOD_PASSPORT!=='undefined'&&typeof SAIGON_DRINK_PASSPORT!=='undefined'){
  const arr=type==='drink'?SAIGON_DRINK_PASSPORT:SAIGON_FOOD_PASSPORT;const done=arr.filter(x=>typeof passTried==='function'&&passTried(type,x.id)).length;return `<div class="tc1PassHead"><h2>${type==='drink'?'Coffee & Drink':'Saigon Food'} Passport</h2><p>${done} / ${arr.length} tried · your original curated ${arr.length}-item collection is preserved.</p></div><div class="tc1PassSwitcher"><button class="${type==='food'?'on':''}" data-pass-type="food">FOOD · ${SAIGON_FOOD_PASSPORT.length}</button><button class="${type==='drink'?'on':''}" data-pass-type="drink">DRINKS · ${SAIGON_DRINK_PASSPORT.length}</button></div><div class="tc1PassGrid">${arr.map(x=>{const tried=typeof passTried==='function'&&passTried(type,x.id),saved=!!(state.saved&&state.saved['passport-'+type+'-'+x.id]);return `<article class="tc1Pass"><div class="tc1PassPhoto vnFallback" data-vnimg="${esc(x.name)}" data-label="${esc(x.name)}"></div><div class="tc1PassBody"><div class="en">${esc(x.en)}</div><h3>${esc(x.name)}</h3><p>${esc(x.desc)}</p><div class="tc1PassMeta">${esc(x.price)} · ${esc(x.when)}</div>${tried?'<div class="tc1Stamp">✓ TRIED IN SAIGON</div>':''}<div class="tc1PassBtns"><button class="${saved?'on':''}" data-pass-save="${esc(x.id)}">${saved?'♥ SAVED':'♡ SAVE'}</button><button class="${tried?'on':''}" data-pass-tried="${esc(x.id)}">${tried?'✓ TRIED':'I TRIED THIS'}</button></div></div></article>`}).join('')}</div>`;
 }
 const food=foodPassportItems(id,i),drink=destinationDrinks(id,i);
 if(type==='food')return `<div class="tc1PassHead"><h2>Food Passport</h2><p>${food.length} local or regional dishes selected for ${esc(destinations(id)[i]?.name||'this stop')}. Costs are planning estimates in AUD.</p></div><div class="tc1PassSwitcher"><button class="on" data-pass-type="food">FOOD · ${food.length}</button><button data-pass-type="drink">DRINKS · ${drink.length}</button></div><div class="tc1PassGrid tc1FoodPassGrid">${food.map(it=>foodPassportCard(id,i,it)).join('')}</div>`;
 const arr=drink;return `<div class="tc1PassHead"><h2>Drink Passport</h2><p>${arr.length?arr.length+' destination-specific drink or coffee experiences from the experience bank.':'No separate drink passport has been curated here yet. The food passport remains complete.'}</p></div><div class="tc1PassSwitcher"><button data-pass-type="food">FOOD · ${food.length}</button><button class="on" data-pass-type="drink">DRINKS · ${drink.length}</button></div>${arr.length?`<div class="tc1ExpList">${arr.map(it=>{const j=it.index;return `<article class="tc1Exp"><div class="tc1ExpCopy"><h3>${esc(it.title)}</h3><p>${esc(it.summary)}</p><div class="tc1Actions"><button class="${hasState('saved',id,i,it,j)?'on':''}" data-save-exp="${j}">${hasState('saved',id,i,it,j)?'♥ SAVED':'♡ SAVE'}</button><button class="${hasState('done',id,i,it,j)?'on':''}" data-done-exp="${j}">${hasState('done',id,i,it,j)?'✓ TRIED':'MARK TRIED'}</button><button class="detail" data-open-exp="${j}">DETAILS →</button></div></div></article>`}).join('')}</div>`:'<div class="tc1Empty">No separate drink items here yet. This does not affect the destination food passport.</div>'}`;
}
function wirePassport(id,i,type){
 document.querySelectorAll('[data-pass-type]').forEach(b=>b.onclick=()=>renderDestination(id,i,'food','All',b.dataset.passType));
 document.querySelectorAll('[data-pass-tried]').forEach(b=>b.onclick=()=>{if(typeof togglePass==='function'){togglePass(type,b.dataset.passTried);renderDestination(id,i,'food','All',type)}});
 document.querySelectorAll('[data-pass-save]').forEach(b=>b.onclick=()=>{state.saved=state.saved||{};const k='passport-'+type+'-'+b.dataset.passSave;state.saved[k]=!state.saved[k];save();renderDestination(id,i,'food','All',type)});
 document.querySelectorAll('[data-food-tried]').forEach(b=>b.onclick=()=>{const it=foodPassportItems(id,i).find(x=>(x.dishId||x.id)===b.dataset.foodTried);if(it){toggleFoodTried(id,i,it);renderDestination(id,i,'food','All','food')}});
 document.querySelectorAll('[data-food-save]').forEach(b=>b.onclick=()=>{const it=foodPassportItems(id,i).find(x=>(x.dishId||x.id)===b.dataset.foodSave);if(it){toggleFoodSaved(id,i,it);renderDestination(id,i,'food','All','food')}});
}
function mapView(id,i){const ds=destinations(id),prev=ds[i-1],next=ds[i+1],d=ds[i];return `<div class="tc1MapPanel"><div class="tc1MapCard"><div class="tc1Scope" style="color:#fff">Route context</div><h2>${esc(d.name)}</h2><p>The redesigned map tab keeps geography contextual. Browsing this page does not change your current location.</p><div class="tc1MapNeighbours">${prev?`<button data-neighbour="${i-1}">← ${esc(prev.name)}</button>`:''}<button disabled>● ${esc(d.name)}</button>${next?`<button data-neighbour="${i+1}">${esc(next.name)} →</button>`:''}</div></div></div>`}
function hcmExtra(title){try{if(typeof HCMC30==='undefined')return null;const n=slug(title);return HCMC30.find(x=>slug(x.title)===n||n.includes(slug(x.title))||slug(x.title).includes(n))||null}catch(e){return null}}
async function renderDetail(id,i,j){await readyCountry(id);const d=destinations(id)[i],it=getItems(id,i).find(x=>x.index===j);if(!it)return renderDestination(id,i,'experiences');V.last='detail';const extra=id==='vietnam'&&i===0?hcmExtra(it.title):null,raw=it.raw||{},facts=[['Priority',it.tier||'Saved'],['Booking',it.booking||raw.booking||it.flags?.join(' · ')||'Usually flexible'],['Time',it.time||extra?.time||raw.time||raw.duration||'Flexible'],['Indicative cost',it.cost||extra?.cost||raw.cost||'Check locally'],['Best time',it.best||extra?.best||raw.best||'Depends on conditions'],['Content value',raw.content||'Optional']];const attrs='class="tc1DetailHero tc1DetailTextHero"';setApp(`<section class="tc1Screen"><div ${attrs}>${topButtons(`data-back-dest="${id}:${i}"`)}<div class="tc1DetailTitle"><div class="tc1Scope" style="color:#fff">${esc(d.name)} · ${esc((it.tags||[]).slice(0,2).join(' · ')||it.tier||'Experience')}</div><h1>${esc(it.title)}</h1><p>${esc(it.summary||'')}</p></div></div><div class="tc1DetailBody"><div class="tc1DetailBlock"><h2>Why go</h2><p>${esc(it.why||it.summary||d.context||d.summary||'This experience is part of the saved destination bank.')}</p></div>${it.action?`<div class="tc1DetailBlock"><h2>What you'll actually do</h2><p>${esc(it.action)}</p></div>`:''}${extra?.do?.length?`<div class="tc1DetailBlock"><h2>Do</h2><ul>${extra.do.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}<div class="tc1DetailBlock"><h2>Good to know</h2><div class="tc1FactGrid">${facts.map(([a,b])=>`<div class="tc1Fact"><small>${esc(a)}</small><b>${esc(b)}</b></div>`).join('')}</div></div>${d.context?`<div class="tc1DetailBlock"><h2>Destination context</h2><p>${esc(d.context)}</p></div>`:''}<div class="tc1DetailActions"><button class="save" data-detail-save>${hasState('saved',id,i,it,j)?'♥ SAVED':'♡ SAVE'}</button><button class="done" data-detail-done>${hasState('done',id,i,it,j)?'✓ COMPLETED':'MARK COMPLETE'}</button></div></div>${drawer()}</section>`);document.querySelector('[data-back-dest]').onclick=()=>renderDestination(id,i,'experiences');document.querySelector('[data-detail-save]').onclick=()=>{toggleSaved(id,i,it,j);renderDetail(id,i,j)};document.querySelector('[data-detail-done]').onclick=()=>{toggleDone(id,i,it,j);renderDetail(id,i,j)};}
'''

if 'function experienceList(id,i,filter)' not in s:
    marker='function countryEntries(id)'
    assert marker in s
    s=s.replace(marker, missing+'\n'+marker,1)

old="const photo=showPhoto?`<div class=\"tc1RatePhoto ${id==='vietnam'?'vnFallback':''}\" ${directPhoto?`style=\"background-image:url('${esc(directPhoto)}')\"`:''} ${id==='vietnam'?`data-vnimg=\"${esc(it.title)}\" data-label=\"${esc(it.title)}\"`:''}></div>`:'';"
new="const photo=showPhoto?(directPhoto?`<div class=\"tc1RatePhoto tc1RatePhotoDirect\" style=\"background-image:url('${esc(directPhoto)}')\" data-direct-photo=\"true\"></div>`:`<div class=\"tc1RatePhoto ${id==='vietnam'?'vnFallback':''}\" ${id==='vietnam'?`data-vnimg=\"${esc(it.title)}\" data-label=\"${esc(it.title)}\"`:''}></div>`):'';"
assert old in s, 'rater photo marker not found'
s=s.replace(old,new,1)
p.write_text(s)

# Add a safe image-failure fallback that does not show PHOTO TO VERIFY inside the approved rater.
css=Path('data/rater-cinematic-v2.css')
c=css.read_text()
rule='''\n/* Saigon direct rater photos: never show the legacy PHOTO TO VERIFY overlay. */\n.tc1RatePhotoDirect{background-color:#1a1b20!important}\n.tc1RatePhotoDirect:before{display:none!important}\n'''
if '.tc1RatePhotoDirect' not in c:
    css.write_text(c+rule)
